name: Maven Build

on:
  push:
    branches:
	  - main

jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    - name: checkout project repo
	  uses: actions/checkout@v3
	  
	- name: set up the java
	  uses: actions/setup-java@v4
	  with:
	    java-version: '17'
    - name: run pom.xml file
	  run: mvn clean install
